name: dgo
description: Interop between Dart and Go on Android.
version: 0.1.0

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  logging: ^1.0.2
  meta: ^1.7.0

dev_dependencies:
  ffigen: ^6.1.2
  import_sorter: ^4.6.0
  lints: ^2.0.0
  quiver: ^3.1.0
  test: ^1.16.0

import_sorter:
  ignored_files:
    - lib/src/dgo_binding.dart

ffigen:
  output: lib/src/dgo_binding.dart
  name: LibDgo
  headers:
    entry-points:
      - ../build/include/go.h
    include-directives:
      - ../build/include/**.h
  functions:
    exclude:
      - "_.*"
      - "dgo__.*"
  structs:
    exclude:
      - "_.*"
      - "dgo__.*"
      - "^Go.*"
  globals:
    exclude:
      - "_.*"
      - "dgo__.*"
